apiVersion: v1
kind: Secret
metadata:
  name: auth-v1-secrets
  namespace: auth
  labels:
    app: auth-v1
type: Opaque
stringData:
  DATABASE_URL: "postgresql+psycopg2://auth:auth@auth-postgres.postgres.svc.cluster.local:5432/auth"
  JWT_SECRET: "M/AzYyBJrECM2uf4NgLUXXUL8N7apk5p25vvQJEYhzpJyI/d0lhQdKSJ5jUA3yaG"
 