apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-v1-config
  namespace: auth
  labels:
    app: auth-v1 
data:
  JWT_ALGORITHM: "HS256"
  ACCESS_TOKEN_TTL_SECONDS: "900"
  REFRESH_TOKEN_TTL_SECONDS: "604800"
