apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: postgres
  labels:
    app: postgres
type: Opaque
stringData:
  POSTGRES_USER: "auth"
  POSTGRES_PASSWORD: "auth"
  POSTGRES_DB: "auth"