FROM python:3.12.1-slim-bookworm
WORKDIR /app


RUN useradd -m -s /bin/bash appuser


COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


COPY . .


USER appuser

EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
